# -*- coding: utf-8 -*-
"""
PEP 六年级上册（2024/2026 新教材）Unit 1-6 课本内容。
数据来源：教材知识清单公开预览 + 单元讲义；可用 fetch_textbook_data.py 辅助更新。
"""
# pylint: disable=line-too-long

# vocab: (word, ipa, pos, chinese)
# phrase/sentence: (english, chinese)

UNITS = [
    {
        "num": 1,
        "title": "Amazing places",
        "title_cn": "奇妙之地",
        "theme": "旅行与著名地标（中外名胜、红色文化景点）",
        "goals": [
            "听懂并说出本单元核心词汇与短语",
            "用一般过去时描述旅行经历",
            "运用 by + 交通工具表达出行方式",
            "读懂并复述课文，介绍著名景点",
        ],
        "learning_map": {
            "Places 景点": ["Great Wall", "Eiffel Tower", "Terracotta Warriors", "Gingerbread House"],
            "Activities 活动": ["climb", "visit", "see", "eat", "take photos"],
            "Transport 交通": ["by train", "by plane", "by bus", "by cable car"],
            "Culture 文化": ["bamboo forest", "red culture", "inspiring stories"],
        },
        "part_a_vocab": [
            ("was", "/wɒz/", "v.", "是（am/is 的过去式）"),
            ("climb", "/klaɪm/", "v.", "攀登；爬"),
            ("go", "/ɡəʊ/", "v.", "去"),
            ("see", "/siː/", "v.", "看见"),
            ("eat", "/iːt/", "v.", "吃"),
            ("take", "/teɪk/", "v.", "拍摄；拿"),
            ("send", "/send/", "v.", "邮寄；发送"),
            ("kilometre", "/ˈkɪləmiːtə(r)/", "n.", "千米"),
            ("thousand", "/ˈθaʊznd/", "num.", "一千"),
            ("view", "/vjuː/", "n.", "景色；风景"),
            ("amazing", "/əˈmeɪzɪŋ/", "adj.", "极好的；令人惊奇的"),
            ("Great Wall", "/ɡreɪt wɔːl/", "n.", "长城"),
            ("Gingerbread House", "/ˈdʒɪndʒəbred haʊs/", "n.", "姜饼屋"),
            ("Eiffel Tower", "/ˈaɪfl ˈtaʊə(r)/", "n.", "埃菲尔铁塔"),
        ],
        "part_b_vocab": [
            ("village", "/ˈvɪlɪdʒ/", "n.", "村庄"),
            ("dry", "/draɪ/", "adj.", "干的"),
            ("clay", "/kleɪ/", "n.", "黏土；陶土"),
            ("inspiring", "/ɪnˈspaɪərɪŋ/", "adj.", "鼓舞人心的"),
            ("bamboo", "/ˌbæmˈbuː/", "n.", "竹子"),
            ("pumpkin", "/ˈpʌmpkɪn/", "n.", "南瓜"),
            ("restaurant", "/ˈrestrɒnt/", "n.", "餐馆"),
            ("airport", "/ˈeəpɔːt/", "n.", "机场"),
            ("Terracotta Warriors", "/ˌterəˈkɒtə ˈwɒriəz/", "n.", "兵马俑"),
            ("Jinggangshan Revolution Museum", "/dʒɪŋˈɡæŋʃæn/", "n.", "井冈山革命博物馆"),
            ("Hong Kong-Zhuhai-Macao Bridge", "/brɪdʒ/", "n.", "港珠澳大桥"),
        ],
        "part_a_phrases": [
            ("climb the Great Wall", "爬长城"),
            ("last weekend", "上周末"),
            ("over the summer holidays", "暑假期间"),
            ("take many photos", "拍很多照片"),
            ("a must-see attraction", "必游景点"),
            ("visit the Gingerbread House", "参观姜饼屋"),
            ("send me some pictures", "给我发一些照片"),
            ("walk around the Palace Museum", "逛故宫博物院"),
        ],
        "part_b_phrases": [
            ("go to Xi'an", "去西安"),
            ("eat Xi'an noodles", "吃西安面条"),
            ("see the Terracotta Warriors", "看兵马俑"),
            ("ride bikes on the old city wall", "在古城墙上骑自行车"),
            ("the bamboo forest", "竹林"),
            ("pumpkin soup", "南瓜汤"),
            ("red rice", "红米饭"),
            ("by high-speed train", "乘高铁"),
            ("by cable car", "乘缆车"),
        ],
        "part_a_sentences": [
            ("— How was your weekend / holiday?", "— 你周末/假期过得怎么样？"),
            ("— It was great / fun / amazing!", "— 非常棒！/ 很有趣！/ 太棒了！"),
            ("— What did you do last Saturday?", "— 你上周六做了什么？"),
            ("— I visited the Gingerbread House.", "— 我参观了姜饼屋。"),
            ("— Please send me some pictures.", "— 请发给我一些照片。"),
            ("— That sounds interesting.", "— 那听起来很有趣。"),
        ],
        "part_b_sentences": [
            ("— Where did you go over the summer holidays?", "— 你暑假去哪儿了？"),
            ("— I went to Xi'an with my family.", "— 我和家人去了西安。"),
            ("— What did you do there?", "— 你们在那儿做了什么？"),
            ("— We went to see the Terracotta Warriors.", "— 我们去看了兵马俑。"),
            ("— Did you climb the Great Wall?", "— 你爬长城了吗？"),
            ("— Yes, I did. / No, I didn't.", "— 是的，我爬了。/ 不，我没有。"),
            ("The Great Wall is 21,000 kilometres in all.", "长城全长 21000 公里。"),
            ("There are over seven thousand clay warriors and one hundred horses.", "那里有七千多个陶俑和一百匹马。"),
            ("The stories were really inspiring.", "那些故事非常鼓舞人心。"),
        ],
        "reading_title": "My Trip to Xi'an",
        "reading_text": (
            "Last summer, Chen Jie went to Xi'an with her family. They ate famous Xi'an noodles "
            "and visited the Terracotta Warriors. There were over seven thousand clay warriors. "
            "Sarah went to the Jinggangshan Revolution Museum. The stories were really inspiring."
        ),
        "reading_keywords": ["went", "visited", "Terracotta Warriors", "noodles", "inspiring"],
        "grammar_discover": {
            "title": "一般过去时 Past Simple",
            "observe": [
                ("I climbed the Great Wall last weekend.", "我上周末爬了长城。"),
                ("I didn't go to Beijing.", "我没去北京。"),
                ("Did you climb the Great Wall? — Yes, I did.", "你爬长城了吗？— 是的。"),
                ("What did you do? — I went to Xi'an.", "你做了什么？— 我去了西安。"),
            ],
            "hints": [
                "动词变成过去式：climb→climbed, visit→visited",
                "否定用 didn't + 动词原形",
                "疑问用 Did + 主语 + 动词原形?",
                "不规则动词：go→went, see→saw, eat→ate, take→took",
            ],
        },
        "mini_challenge": [
            "用过去时写一句：你上周末做了什么？",
            "写出 3 个不规则动词过去式：go→___  see→___  eat→___",
            "填空：I ___ (visit) the Great Wall last year.",
            "翻译：你暑假去哪儿了？",
            "用 by + 交通工具造句：",
        ],
        "learning_tip": "听懂、会读、会用，比死记硬背更重要。",
    },
    {
        "num": 2,
        "title": "Getting together",
        "title_cn": "相聚在一起",
        "theme": "中外传统节日与家庭聚会",
        "goals": [
            "听懂并说出节日相关词汇",
            "用一般过去时描述节日活动",
            "用一般疑问句 Did you...? 询问过去经历",
            "了解中外节日文化",
        ],
        "learning_map": {
            "Festivals 节日": ["Spring Festival", "Mid-Autumn Festival", "Dragon Boat Festival"],
            "Activities 活动": ["paste fu", "dress in red", "count down", "cheer"],
            "Food 食物": ["mooncakes", "zongzi", "jiaozi"],
            "Events 活动": ["marathon", "book fair", "dragon boat race"],
        },
        "part_a_vocab": [
            ("dress", "/dres/", "v.", "穿衣服"),
            ("paste", "/peɪst/", "v.", "粘贴"),
            ("gala", "/ˈɡɑːlə/", "n.", "演出；庆典"),
            ("count down", "/kaʊnt daʊn/", "phr.", "倒计时"),
            ("marathon", "/ˈmærəθən/", "n.", "马拉松"),
            ("cheer", "/tʃɪə(r)/", "v.", "欢呼；加油"),
            ("book fair", "/bʊk feə(r)/", "n.", "书市"),
            ("yesterday", "/ˈjestədeɪ/", "adv.", "昨天"),
            ("exciting", "/ɪkˈsaɪtɪŋ/", "adj.", "令人激动的"),
        ],
        "part_b_vocab": [
            ("race", "/reɪs/", "n.", "赛跑"),
            ("run", "/rʌn/", "v.", "跑"),
            ("winner", "/ˈwɪnə(r)/", "n.", "获胜者"),
            ("wake", "/weɪk/", "v.", "醒；醒来"),
            ("begin", "/bɪˈɡɪn/", "v.", "开始"),
            ("win", "/wɪn/", "v.", "获胜"),
            ("share", "/ʃeə(r)/", "v.", "分享"),
            ("make zongzi", "/meɪk ˈzɒŋzi/", "phr.", "包粽子"),
        ],
        "part_a_phrases": [
            ("paste fu on the door", "在门上贴福字"),
            ("dress in red", "穿红色衣服"),
            ("wait for the Spring Festival Gala", "等待春节联欢晚会"),
            ("count down to the new year", "倒计时迎接新年"),
            ("clean the house", "打扫房子"),
            ("have a big dinner", "吃一顿大餐"),
        ],
        "part_b_phrases": [
            ("go to a marathon", "参加马拉松"),
            ("work as a volunteer", "作为志愿者工作"),
            ("cheer for the runners", "为跑步者加油"),
            ("join an online book fair", "参加线上书市"),
            ("share ideas", "分享想法"),
            ("the dragon boat race", "龙舟赛"),
            ("wake up early", "早起"),
            ("make zongzi", "包粽子"),
        ],
        "part_a_sentences": [
            ("— How was your Mid-Autumn Festival holiday, Binbin?", "— 你中秋假期过得怎么样？"),
            ("— Did you eat mooncakes?", "— 你们吃月饼了吗？"),
            ("— Yes, we did. / No, we didn't.", "— 是的。/ 不，没有。"),
            ("— What did you do for the Spring Festival?", "— 你春节做了什么？"),
        ],
        "part_b_sentences": [
            ("— Did you take a trip?", "— 你们去旅行了吗？"),
            ("— What did you like about it?", "— 你喜欢哪一点？"),
            ("— I liked watching the runners.", "— 我喜欢看跑步的人。"),
            ("My dad and I cleaned the house.", "我爸爸和我打扫了房子。"),
            ("We dressed in red and counted down to the new year.", "我们穿红衣，倒计时迎接新年。"),
            ("We enjoyed some mooncakes and fruit.", "我们吃了美味的月饼和水果。"),
            ("We can paste fu and eat jiaozi together.", "我们可以一起贴福字、吃饺子。"),
            ("Finally, his team won the race!", "最后，他的队伍赢得了比赛！"),
            ("It was the best Dragon Boat Festival ever!", "这是有史以来最好的端午节！"),
        ],
        "reading_title": "The Spring Festival",
        "reading_text": (
            "The Spring Festival was great fun! My family cleaned the house and pasted fu on the door. "
            "We dressed in red and waited for the Spring Festival Gala. We counted down to the new year. "
            "We enjoyed mooncakes and fruit. It was the best festival ever!"
        ),
        "reading_keywords": ["Spring Festival", "paste fu", "dress in red", "mooncakes", "count down"],
        "grammar_discover": {
            "title": "一般过去时疑问句 Did you...?",
            "observe": [
                ("Did you eat mooncakes? — Yes, we did.", "你们吃月饼了吗？— 是的。"),
                ("Did you take a trip? — No, we didn't.", "你们去旅行了吗？— 没有。"),
                ("clean → cleaned    paste → pasted", "规则动词加 -ed"),
                ("run → ran    eat → ate", "不规则动词要牢记"),
            ],
            "hints": [
                "Did + 主语 + 动词原形?",
                "肯定答：Yes, 主语 + did.",
                "否定答：No, 主语 + didn't.",
                "助动词 did 后动词必须用原形",
            ],
        },
        "mini_challenge": [
            "写出 paste 的过去式：___",
            "Did you ___ (watch) fireworks? 填原形",
            "翻译：你们吃月饼了吗？",
            "用 Yes, we did. 回答一个问题",
            "写出 2 个节日活动短语：",
        ],
        "learning_tip": "用顺序词讲故事，比背句子更有用。",
    },
    {
        "num": 3,
        "title": "Healthy life",
        "title_cn": "健康生活",
        "theme": "身体健康、疾病表达与健康生活习惯",
        "goals": [
            "描述身体状况，询问 How do you feel?",
            "用 should 给出健康建议",
            "用 be going to 表达健康计划",
            "了解身心健康的重要性",
        ],
        "learning_map": {
            "Illness 疾病": ["cold", "fever", "cough", "runny nose"],
            "Advice 建议": ["see a doctor", "get well soon", "healthy diet"],
            "Habits 习惯": ["exercise often", "stay up", "join clubs"],
            "Feelings 感受": ["feel ill", "unhappy", "cheer you up"],
        },
        "part_a_vocab": [
            ("cold", "/kəʊld/", "n.", "感冒"),
            ("ill", "/ɪl/", "adj.", "不舒服；有病"),
            ("head", "/hed/", "n.", "头"),
            ("runny nose", "/ˈrʌni nəʊz/", "n.", "流鼻涕"),
            ("fever", "/ˈfiːvə(r)/", "n.", "发烧"),
            ("cough", "/kɒf/", "n./v.", "咳嗽"),
            ("soon", "/suːn/", "adv.", "很快"),
            ("hospital", "/ˈhɒspɪtl/", "n.", "医院"),
            ("better", "/ˈbetə(r)/", "adj.", "好转的"),
        ],
        "part_b_vocab": [
            ("diet", "/ˈdaɪət/", "n.", "日常饮食"),
            ("stay up", "/steɪ ʌp/", "phr.", "熬夜"),
            ("unhappy", "/ʌnˈhæpi/", "adj.", "不快乐的"),
            ("video", "/ˈvɪdiəʊ/", "n.", "视频"),
            ("should", "/ʃʊd/", "modal v.", "应该"),
            ("exercise", "/ˈeksəsaɪz/", "n./v.", "锻炼"),
            ("healthy", "/ˈhelθi/", "adj.", "健康的"),
            ("club", "/klʌb/", "n.", "俱乐部"),
        ],
        "part_a_phrases": [
            ("have a bad cold", "得了重感冒"),
            ("have a fever", "发烧"),
            ("have a cough", "咳嗽"),
            ("see a doctor", "看医生"),
            ("go to hospital", "去医院"),
            ("get well soon", "早日康复"),
        ],
        "part_b_phrases": [
            ("have a healthy diet", "保持健康饮食"),
            ("exercise often", "经常锻炼"),
            ("think about happy things", "想开心的事情"),
            ("join clubs and teams", "加入俱乐部和团队"),
            ("make video calls", "打视频电话"),
            ("cheer you up", "让你振作起来"),
        ],
        "part_a_sentences": [
            ("— How do you feel?", "— 你感觉怎么样？"),
            ("— I feel ill. My head hurts and I have a runny nose.", "— 我感觉不舒服。我头痛还流鼻涕。"),
            ("— Maybe you should see a doctor.", "— 也许你应该去看医生。"),
            ("— You shouldn't stay up late.", "— 你不应该熬夜。"),
        ],
        "part_b_sentences": [
            ("— How can we live a healthy life?", "— 我们怎样过健康生活？"),
            ("— We need to eat healthy food. We should exercise too.", "— 我们需要吃健康食物，还应该运动。"),
            ("— What are you going to do?", "— 你打算做什么？"),
            ("— I'm going to see a doctor.", "— 我打算去看医生。"),
            ("My mum is going to take me to hospital this afternoon.", "我妈妈今天下午要带我去医院。"),
            ("Health is having a good body and feeling happy.", "健康是拥有健康的身体和快乐的心情。"),
            ("Exercise may cheer you up!", "运动可能会让你振作起来！"),
            ("I also joined a ping-pong club and made some new friends.", "我还加入了乒乓球俱乐部，交了一些新朋友。"),
        ],
        "reading_title": "How to Keep Healthy",
        "reading_text": (
            "Health is very important. You should eat healthy food and exercise often. "
            "You shouldn't stay up late. If you feel ill, you should see a doctor. "
            "Think about happy things and join clubs. Let's live a healthy life together!"
        ),
        "reading_keywords": ["healthy", "exercise", "should", "see a doctor", "cheer you up"],
        "grammar_discover": {
            "title": "should / shouldn't & be going to",
            "observe": [
                ("You should exercise.", "你应该锻炼。"),
                ("You shouldn't stay up late.", "你不应该熬夜。"),
                ("I am going to see a doctor.", "我打算去看医生。"),
                ("My head hurts.", "我头痛。（一般现在时）"),
            ],
            "hints": [
                "should 表示建议「应该」",
                "shouldn't = should not",
                "be going to + 动词原形 = 打算",
                "描述症状用一般现在时",
            ],
        },
        "mini_challenge": [
            "填空：You ___ (should/shouldn't) exercise every day.",
            "翻译：也许你应该去看医生。",
            "用 be going to 写一句健康计划",
            "What's wrong? 怎么回答「我头痛」？",
            "写出 3 个疾病词汇：",
        ],
        "learning_tip": "健康不仅是身体，心情也很重要。",
    },
    {
        "num": 4,
        "title": "Managing money well",
        "title_cn": "合理管理金钱",
        "theme": "零花钱管理、理性消费与储蓄",
        "goals": [
            "谈论用钱计划",
            "用 be going to 表达打算",
            "区分 need 和 want",
            "学会量入为出、合理储蓄",
        ],
        "learning_map": {
            "Money 金钱": ["pocket money", "lucky money", "cash", "price"],
            "Actions 行为": ["save", "spend", "buy", "pay"],
            "Items 物品": ["piggy bank", "schoolbag", "goods"],
            "Plans 计划": ["save up", "wait for a sale", "spending plan"],
        },
        "part_a_vocab": [
            ("money", "/ˈmʌni/", "n.", "钱"),
            ("pocket money", "/ˈpɒkɪt ˈmʌni/", "n.", "零花钱"),
            ("schoolbag", "/ˈskuːlbæɡ/", "n.", "书包"),
            ("goods", "/ɡʊdz/", "n.", "商品"),
            ("service", "/ˈsɜːvɪs/", "n.", "服务"),
            ("drink", "/drɪŋk/", "n.", "饮料"),
            ("buy", "/baɪ/", "v.", "买"),
            ("spend", "/spend/", "v.", "花费"),
        ],
        "part_b_vocab": [
            ("save", "/seɪv/", "v.", "储蓄"),
            ("save up", "/seɪv ʌp/", "phr.", "攒钱"),
            ("sale", "/seɪl/", "n.", "打折出售"),
            ("ticket", "/ˈtɪkɪt/", "n.", "票"),
            ("manage", "/ˈmænɪdʒ/", "v.", "管理"),
            ("need", "/niːd/", "v.", "需要"),
            ("want", "/wɒnt/", "v.", "想要"),
            ("plan", "/plæn/", "n./v.", "计划"),
            ("half", "/hɑːf/", "n.", "一半"),
        ],
        "part_a_phrases": [
            ("pocket money", "零花钱"),
            ("buy goods", "购买商品"),
            ("pay for services", "支付服务费用"),
            ("a cold drink", "一杯冷饮"),
            ("spend pocket money", "花零花钱"),
        ],
        "part_b_phrases": [
            ("save up for a computer", "攒钱买电脑"),
            ("write a spending plan", "写花钱计划"),
            ("wait for a sale", "等打折"),
            ("be careful with money", "谨慎用钱"),
            ("buy a nice gift", "买一份漂亮的礼物"),
            ("use money wisely", "明智地用钱"),
        ],
        "part_a_sentences": [
            ("— How are you going to spend your pocket money?", "— 你打算怎么花零花钱？"),
            ("— I am going to buy a schoolbag.", "— 我打算买一个书包。"),
            ("— We use money to buy goods.", "— 我们用钱买商品。"),
            ("— We use money to pay for services.", "— 我们用钱支付服务。"),
        ],
        "part_b_sentences": [
            ("— I also want to buy some books.", "— 我还想买一些书。"),
            ("— I need to save more.", "— 我需要多存钱。"),
            ("— Should I also buy some ice cream?", "— 我也应该买冰淇淋吗？"),
            ("— Sure, but don't eat too much.", "— 当然，但不要吃太多。"),
            ("— I have 50 yuan. What should I do?", "— 我有 50 元。我应该怎么办？"),
            ("— Maybe you can wait for a sale.", "— 也许你可以等打折。"),
            ("Mike is going to save up for a computer.", "迈克打算攒钱买电脑。"),
            ("Liu Jia is going to wait for a sale.", "刘佳打算等打折再买。"),
        ],
        "reading_title": "How I Manage My Pocket Money",
        "reading_text": (
            "I get some pocket money every month. I am going to save half of it in my piggy bank. "
            "I want to save up for a new basketball. I also want to buy some books on sale. "
            "I shouldn't waste money on things I don't need."
        ),
        "reading_keywords": ["pocket money", "save", "spending plan", "on sale", "goods"],
        "grammar_discover": {
            "title": "be going to & want/need to do",
            "observe": [
                ("How are you going to spend it?", "你打算怎么花？"),
                ("I am going to buy a schoolbag.", "我打算买书包。"),
                ("I want to buy some books.", "我想买书。"),
                ("I need to save more.", "我需要多存钱。"),
            ],
            "hints": [
                "be going to + 动词原形 = 打算",
                "want to do = 想要做",
                "need to do = 需要做",
                "use...to... 表示用途",
            ],
        },
        "mini_challenge": [
            "翻译：我打算攒钱买一辆新自行车。",
            "填空：I want ___ (buy) a dictionary.",
            "need 和 want 有什么区别？",
            "用 be going to 写一句用钱计划",
            "写出 3 个与钱有关的词：",
        ],
        "learning_tip": "先分清 need 和 want，再决定怎么花钱。",
    },
    {
        "num": 5,
        "title": "Exploring space",
        "title_cn": "探索太空",
        "theme": "太空探索、宇宙天体与中国航天成就",
        "goals": [
            "用 There be 描述太空事物",
            "用 can / can't 表达能力",
            "了解太阳系与中国航天成就",
            "用一般过去时谈论太空探索",
        ],
        "learning_map": {
            "Space 太空": ["space", "planet", "star", "moon", "Mars"],
            "Objects 物体": ["rocket", "spaceship", "telescope", "space station"],
            "People 人物": ["astronaut"],
            "China 中国": ["rover", "red planet", "solar system"],
        },
        "part_a_vocab": [
            ("space", "/speɪs/", "n.", "太空"),
            ("planet", "/ˈplænɪt/", "n.", "行星"),
            ("star", "/stɑː(r)/", "n.", "星星"),
            ("moon", "/muːn/", "n.", "月亮"),
            ("Earth", "/ɜːθ/", "n.", "地球"),
            ("sky", "/skaɪ/", "n.", "天空"),
            ("telescope", "/ˈtelɪskəʊp/", "n.", "望远镜"),
            ("spaceship", "/ˈspeɪsʃɪp/", "n.", "宇宙飞船"),
        ],
        "part_b_vocab": [
            ("Mars", "/mɑːz/", "n.", "火星"),
            ("astronaut", "/ˈæstrənɔːt/", "n.", "宇航员"),
            ("space station", "/speɪs ˈsteɪʃn/", "n.", "空间站"),
            ("outer space", "/ˈaʊtə speɪs/", "n.", "外太空"),
            ("rover", "/ˈrəʊvə(r)/", "n.", "探测器"),
            ("soil", "/sɔɪl/", "n.", "土壤"),
            ("solar system", "/ˈsəʊlə ˈsɪstəm/", "n.", "太阳系"),
            ("rocket", "/ˈrɒkɪt/", "n.", "火箭"),
        ],
        "part_a_phrases": [
            ("look into space", "观察太空"),
            ("in the solar system", "在太阳系中"),
            ("use a telescope", "使用望远镜"),
            ("travel in outer space", "在外太空旅行"),
            ("in the science museum", "在科学博物馆"),
        ],
        "part_b_phrases": [
            ("explore space", "探索太空"),
            ("live on a space station", "住在空间站"),
            ("the red planet", "红色星球"),
            ("send a rover to Mars", "向火星发送探测器"),
            ("go into space by spaceship", "乘宇宙飞船进入太空"),
            ("make us proud", "让我们自豪"),
        ],
        "part_a_sentences": [
            ("— How can we explore space?", "— 我们怎样探索太空？"),
            ("— We can use telescopes.", "— 我们可以使用望远镜。"),
            ("— What can we see in space?", "— 我们在太空中能看到什么？"),
            ("— We can see stars, planets and the moon.", "— 我们能看到星星、行星和月亮。"),
            ("— There is a big rocket in the museum.", "— 博物馆里有一个大火箭。"),
            ("There are eight planets in our solar system.", "我们的太阳系有八颗行星。"),
        ],
        "part_b_sentences": [
            ("— Can we live on Mars?", "— 我们能住在火星上吗？"),
            ("— No, we can't. / Not yet.", "— 不，不能。/ 还不行。"),
            ("— Where do astronauts live in space?", "— 宇航员住在哪？"),
            ("— On a space station.", "— 在空间站。"),
            ("— What is Mars called?", "— 火星被称为什么？"),
            ("— It is called the \"red planet\".", "— 它被称为「红色星球」。"),
            ("— What did you learn about Mars?", "— 关于火星你了解了什么？"),
            ("— I know it has soil and water.", "— 我知道它有土壤和水。"),
            ("— Did you see the pictures of Mars?", "— 你看到火星的照片了吗？"),
            ("— Yes, I did.", "— 是的，我看到了。"),
            ("China sent a rover to Mars last year.", "中国去年向火星发送了探测器。"),
        ],
        "reading_title": "Exploring Space",
        "reading_text": (
            "Space is amazing! There are many stars and planets in the solar system. "
            "We can use telescopes to look into space. Astronauts live on a space station. "
            "Mars is called the red planet. China sent a rover to Mars. It makes us proud!"
        ),
        "reading_keywords": ["space", "telescope", "space station", "Mars", "rover"],
        "grammar_discover": {
            "title": "There be & can / can't & 一般过去时",
            "observe": [
                ("There is a big rocket.", "有一个大火箭。"),
                ("There are many stars.", "有许多星星。"),
                ("We can use telescopes.", "我们能用望远镜。"),
                ("China sent a rover to Mars.", "中国发送了火星探测器。"),
            ],
            "hints": [
                "There is + 单数 / There are + 复数",
                "can + 动词原形 表示能力",
                "一般过去时：send→sent, use→used",
                "Did you see...? — Yes, I did.",
            ],
        },
        "mini_challenge": [
            "There ___ (is/are) many stars in space.",
            "翻译：我们怎样探索太空？",
            "Can we live on Mars? 怎么回答？",
            "写出 send 的过去式：___",
            "用 can 造句：We can ___ in space.",
        ],
        "learning_tip": "观察句子结构，自己发现 There be 的规律。",
    },
    {
        "num": 6,
        "title": "Energy, nature and us",
        "title_cn": "能源、自然与我们",
        "theme": "能源来源、环保与 3R 原则",
        "goals": [
            "询问能源来源 Where does...come from?",
            "用 should 提出环保建议",
            "了解绿色能源与 3R 原则",
            "养成节约能源的习惯",
        ],
        "learning_map": {
            "Energy 能源": ["electricity", "solar power", "wind power", "water power"],
            "Actions 行动": ["save energy", "reduce", "reuse", "recycle"],
            "Objects 物品": ["power station", "air conditioner", "LED lighting"],
            "Nature 自然": ["water", "wind", "sun", "Earth"],
        },
        "part_a_vocab": [
            ("energy", "/ˈenədʒi/", "n.", "能源"),
            ("electricity", "/ɪˌlekˈtrɪsəti/", "n.", "电"),
            ("solar power", "/ˈsəʊlə ˈpaʊə(r)/", "n.", "太阳能"),
            ("wind power", "/wɪnd ˈpaʊə(r)/", "n.", "风能"),
            ("water power", "/ˈwɔːtə ˈpaʊə(r)/", "n.", "水能"),
            ("green energy", "/ɡriːn ˈenədʒi/", "n.", "绿色能源"),
            ("power station", "/ˈpaʊə ˈsteɪʃn/", "n.", "发电站"),
            ("come from", "/kʌm frɒm/", "phr.", "来自"),
        ],
        "part_b_vocab": [
            ("reduce", "/rɪˈdjuːs/", "v.", "减少"),
            ("reuse", "/ˌriːˈjuːz/", "v.", "重复使用"),
            ("recycle", "/ˌriːˈsaɪkl/", "v.", "回收利用"),
            ("unplug", "/ʌnˈplʌɡ/", "v.", "拔掉插头"),
            ("air conditioner", "/eə kənˈdɪʃənə(r)/", "n.", "空调"),
            ("shower", "/ˈʃaʊə(r)/", "n./v.", "淋浴"),
            ("LED lighting", "/ˌel iː ˈdiː/", "n.", "LED 照明"),
            ("save energy", "/seɪv ˈenədʒi/", "phr.", "节约能源"),
        ],
        "part_a_phrases": [
            ("come from rivers and lakes", "来自江河湖泊"),
            ("make electricity", "发电"),
            ("green energy", "绿色能源"),
            ("turn off lights", "关灯"),
            ("save energy", "节约能源"),
        ],
        "part_b_phrases": [
            ("take quick showers", "快速淋浴"),
            ("the 3R rules", "3R 原则"),
            ("protect the Earth", "保护地球"),
            ("unplug the computer", "拔掉电脑插头"),
            ("use LED lighting", "使用 LED 照明"),
            ("reduce, reuse and recycle", "减少、重复使用、回收"),
        ],
        "part_a_sentences": [
            ("— Where does water come from?", "— 水来自哪里？"),
            ("— It comes from rivers and lakes.", "— 它来自江河湖泊。"),
            ("— Where does electricity come from?", "— 电来自哪里？"),
            ("— It comes from power stations.", "— 它来自发电站。"),
        ],
        "part_b_sentences": [
            ("— How do we make power from water?", "— 我们怎样用水发电？"),
            ("— Water turns the wheel.", "— 水推动水轮。"),
            ("We should save energy and use green energy.", "我们应该节约能源并使用绿色能源。"),
            ("We should always unplug our computers and TVs.", "我们应该不用时拔掉电脑和电视插头。"),
            ("We should save energy every day.", "我们应该每天节约能源。"),
            ("To protect the Earth, we should reduce, reuse and recycle.", "为保护地球，我们应减少、重复使用并回收。"),
            ("We should turn off lights when we leave.", "离开时应关灯。"),
            ("Take quick showers to save water.", "快速淋浴以节约用水。"),
        ],
        "reading_title": "Save Energy, Save the Earth",
        "reading_text": (
            "Energy is important for our life. Water, wind and the sun can make electricity. "
            "They are green energy. We should save energy every day. "
            "We can take quick showers and turn off lights. "
            "To follow the 3R rules, we should reduce, reuse and recycle."
        ),
        "reading_keywords": ["energy", "green energy", "save", "3R", "recycle"],
        "grammar_discover": {
            "title": "Where does...come from? & should",
            "observe": [
                ("Where does water come from?", "水来自哪里？"),
                ("It comes from rivers.", "它来自江河。"),
                ("We should save energy.", "我们应该节约能源。"),
                ("We should reduce, reuse and recycle.", "我们应 3R。"),
            ],
            "hints": [
                "Where does + 单数主语 + come from?",
                "答：It comes from...",
                "should 后接动词原形",
                "3R = Reduce, Reuse, Recycle",
            ],
        },
        "mini_challenge": [
            "翻译：电来自发电站。",
            "3R 代表什么？写出英文：",
            "填空：Where does water ___ (come) from?",
            "用 should 写一句环保建议：",
            "写出 2 种绿色能源：",
        ],
        "learning_tip": "节约能源从小事做起，每天都可以做一点。",
    },
]
